### ISSUE TITLE
Increase CCF version

### ISSUE THREAD

**Issue by LvffY** [cloud-carbon-footprint/ccf-backstage-plugin#9] opened 2022-06-12 10:44 UTC
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**

Because I needed to improve the Azure region support, I contributed to https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/823. Now I would like to know how to integrate these changes in this plugin? 

© 2022 Thoughtworks, Inc.

**Comment by LvffY** [comment] 2022-06-18 08:32
@4upz any thought about this ?

**Comment by 4upz** [comment] 2022-06-22 15:42
Hi @LvffY, we made a new release late last week for both CCF and the backstage plugin which should include your contributions for the Azure region support. Have you tried updating your plugin version to see if these changes are reflected? Or doing a fresh install or for the plugin? 

Let us know if either of those work!

**Comment by LvffY** [comment] 2022-06-22 18:00
@4upz I think I tried this last week, may be a bit ealy tho.

I'll try to test it again :)

**Comment by LvffY** [comment] 2022-06-22 19:41
I think I've found another issue.

I've done the following steps.

```bash
yarn --cwd packages/backend add @cloud-carbon-footprint/backstage-plugin-backend 
yarn --cwd packages/app add @cloud-carbon-footprint/backstage-plugin-frontend
```
Then followed the steps described in the README.

My baskstage instance is running. 

Once on the `/cloud-carbon-footprint` page, I have the following error

![image](https://user-images.githubusercontent.com/37327656/175120704-3b0d3001-503a-4e3e-97c2-d636c966e3c2.png)

Looking at the logs, I have the following lines : 

![image](https://user-images.githubusercontent.com/37327656/175120583-48ee0ec4-89b8-4e3b-859d-aa926d19ae0a.png)

From my understanding, this is related to my use case where I use some Azure DevOps builds. I don't know which use cases are supported through CCF ? 

Is there any configuration that could, temporaly, ignore some VM type or so ?

**Comment by LvffY** [comment] 2022-06-22 20:09
I just found another error lines :

![image](https://user-images.githubusercontent.com/37327656/175127121-f957a490-e184-462d-b44d-3d68614c00a8.png)

**Comment by LvffY** [comment] 2022-06-25 09:35
@4upz It's probably not linked to this particular backstage version, we should probably update the issue title.

But how can we move forward this problem?

**Comment by 4upz** [comment] 2022-07-11 20:53
Hi @LvffY, my apologies for the delayed response! I've been away for a bit but am currently playing catch up. The warnings you're seeing is actually expected behavior, and just mean that the app currently isn't aware of the services you're trying to estimate. This is due to the large variation of Azure services and our ability to only implement them as we come across them.

This is a good thing though, as it's a great opportunity to expand our app some more for your usage types! If you're able, you can contribute changes to the main CCF repository to include these usage types using these instructions: https://www.cloudcarbonfootprint.org/docs/azure#unsupported-usage-types

If you're not interested in contributing this, just let us know! If you provide us with a screenshot of the complete usage types listed, then we can add them for you.

**Comment by LvffY** [comment] 2022-07-12 09:56
@4upz No problem :)

For now I have seen 3 distincts errors : 

- `Unexpected usage type for storage service: Basic User`
- `Unexpected usage type for storage service: Standard Nodes`
- `Unexpected usage type for storage service: Microsoft-hosted CI`

I tried to look into the page you linked but I'm stuck on where to put these values. I actually don't really want to ignore these usages (because they are a big part of my context) so I don't see where to put these values.

Could you help me on this ? (TBH, I could ignore the `Basic User` but I would really want to see the CCF of my CI/CD on Azure DevOps).

One more case : could this be a good idea to have an option to ignore these errors and still have our CCF in our backstage ? 

*For now I just created https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/861 with a fix for a dead link in the doc*

**Comment by 4upz** [comment] 2022-07-12 17:29
@LvffY No worries, you wouldn't be ignoring them. You would instead be adding them as supported usage types for that respective service. So for example, inside of the `ConsumptionTypes.ts`, you would add _Microsoft-hosted CI_ to the `Storage_Usage_Types` constant. The warning gives away which service you should be adding the usage type to. For the example that I chose, it should look like this: 
```javascript
export const STORAGE_USAGE_TYPES: string[] = [
   ...
  'Pay-as-you-go Data at Rest',
  'Standard Instances',
  'Node',
  'Basic User'
]
```

**Comment by 4upz** [comment] 2022-07-12 17:34
As for the error, the unsupported usage types are just logged warnings from the api and aren't actually errors that would break the app. They should only be skipping those services from being included in the estimates. That error may actually be caused by something else -- especially since you seem to still have estimates included in the filters from your screenshot. Would you mind clicking that drop down or providing a screenshot of the inspector error log to see if it shows more details pertaining to that error?

**Comment by LvffY** [comment] 2022-07-13 08:00
@4upz Thanks for your help !

I think I have a working PR in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/861 if you want to take a look. 

For my error (for the first time --') I click on the arrow on the right of the error and I get the following lines 

![Sans titre](https://user-images.githubusercontent.com/37327656/178681094-0ed683e9-dd06-4bcf-9ffd-3d6d14f09c0c.png)

I'm not sure where to look to find this. *May be something related to my configuration ?*

**Comment by 4upz** [comment] 2022-07-13 15:05
Awesome! Thanks, @LvffY. I'll review your PR soon. 

As for the error, thanks for providing the screenshot -- this is extremely helpful. I don't believe its configuration related, but I'll try to replicate and look into this along with the issue in https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/issues/11

**Comment by ericksod** [comment] 2022-07-14 17:14
Closing because the remaining issue will likely be solved with https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/864

**Closed as completed by ericksod** 2022-07-14 17:14 UTC
