### ISSUE TITLE
GCP Carbon foodprint error: Unrecognized name: system_labels

### ISSUE THREAD

**Issue by jonathan-arenas-edo** [cloud-carbon-footprint/ccf-backstage-plugin#74] opened 2023-06-08 11:24 UTC
Hi Guys,

I need your help with Carbon plugin, is not working on my Backstage solution.
I installed the Carbon Plugin following the official documentation for Backstage:
https://github.com/cloud-carbon-footprint/ccf-backstage-plugin

Later, I added the config part on app-config.yaml:
cloudCarbonFootprint:
  gcp:
    useBillingData: true
    billingProjectId: gcp-project
    billingProjectName:  gcp-project
    bigQueryTable: Carbon_Footprint.carbon_footprint

And the plugin is failing with the error: Message: Unrecognized name: system_labels at [18:28]

**Full Error:**

2023-06-08T10:48:41.360Z [api] error: Unable to process footprint request.Error: BigQuery create Query Job failed. Reason: invalidQuery, Location: query, Message: Unrecognized name: system_labels at [18:28]
    at BillingExportTable.createQueryJob (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:384:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BillingExportTable.getUsage (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:357:21)
    at async BillingExportTable.getEstimates (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:30:27)
    at async Object.getCostAndEstimates (/app/node_modules/@cloud-carbon-footprint/app/dist/App.js:52:35)
    at async Promise.all (index 0)
    at async getEstimatesForMissingDates (/app/node_modules/@cloud-carbon-footprint/app/dist/Cache.js:52:13)
    at async App.descriptor.value (/app/node_modules/@cloud-carbon-footprint/app/dist/Cache.js:29:24)
    at async FootprintApiMiddleware (/app/node_modules/@cloud-carbon-footprint/api/dist/api.js:34:35) 
{"level":"info","message":"::ffff:10.87.96.66 - - [08/Jun/2023:10:48:41 +0000] \"GET /api/cloud-carbon-footprint/footprint?start=2023-05-08&end=2023-06-08&ignoreCache=true&groupBy=week HTTP/1.1\" 500 21 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36\"","service":"backstage","type":"incomingRequest"}

Version:
OS:   Darwin 22.4.0 - darwin/arm64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.1

Dependencies:
  @backstage/app-defaults                                   1.3.1
  @backstage/backend-app-api                                0.4.3
  @backstage/backend-common                                 0.17.0, 0.18.5
  @backstage/backend-dev-utils                              0.1.1
  @backstage/backend-plugin-api                             0.5.2
  @backstage/backend-tasks                                  0.5.2
  @backstage/catalog-client                                 1.4.1
  @backstage/catalog-model                                  1.3.0
  @backstage/cli-common                                     0.1.12
  @backstage/cli-node                                       0.1.0
  @backstage/cli                                            0.22.7
  @backstage/config-loader                                  1.3.0
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.8.0
  @backstage/core-components                                0.12.5, 0.13.1
  @backstage/core-plugin-api                                1.5.1
  @backstage/dev-utils                                      1.0.15
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.3
  @backstage/integration-aws-node                           0.1.3
  @backstage/integration-react                              1.1.13
  @backstage/integration                                    1.4.5
  @backstage/plugin-api-docs                                0.9.3
  @backstage/plugin-app-backend                             0.3.45
  @backstage/plugin-auth-backend                            0.17.4, 0.18.3
  @backstage/plugin-auth-node                               0.2.14
  @backstage/plugin-bitbucket-cloud-common                  0.2.6
  @backstage/plugin-catalog-backend-module-bitbucket-cloud  0.1.12
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.10
  @backstage/plugin-catalog-backend-module-gitlab           0.2.1
  @backstage/plugin-catalog-backend-module-ldap             0.5.12
  @backstage/plugin-catalog-backend                         1.9.1
  @backstage/plugin-catalog-common                          1.0.13
  @backstage/plugin-catalog-graph                           0.2.30
  @backstage/plugin-catalog-import                          0.9.8
  @backstage/plugin-catalog-node                            1.3.6
  @backstage/plugin-catalog-react                           1.6.0
  @backstage/plugin-catalog                                 1.11.0
  @backstage/plugin-cost-insights-common                    0.1.1
  @backstage/plugin-cost-insights                           0.12.7
  @backstage/plugin-events-node                             0.2.6
  @backstage/plugin-gcalendar                               0.3.14
  @backstage/plugin-github-actions                          0.5.18
  @backstage/plugin-graphiql                                0.2.50
  @backstage/plugin-home                                    0.5.2
  @backstage/plugin-jenkins-backend                         0.2.0
  @backstage/plugin-jenkins-common                          0.1.15
  @backstage/plugin-jenkins                                 0.8.0
  @backstage/plugin-kubernetes-backend                      0.11.0
  @backstage/plugin-kubernetes-common                       0.6.3
  @backstage/plugin-kubernetes                              0.9.1
  @backstage/plugin-org                                     0.6.8
  @backstage/plugin-pagerduty                               0.5.11
  @backstage/plugin-permission-backend                      0.5.20
  @backstage/plugin-permission-common                       0.7.5
  @backstage/plugin-permission-node                         0.7.8
  @backstage/plugin-permission-react                        0.4.12
  @backstage/plugin-proxy-backend                           0.2.39
  @backstage/plugin-scaffolder-backend                      1.14.0
  @backstage/plugin-scaffolder-common                       1.3.0
  @backstage/plugin-scaffolder-node                         0.1.3
  @backstage/plugin-scaffolder-react                        1.4.0
  @backstage/plugin-scaffolder                              1.13.1
  @backstage/plugin-search-backend-module-catalog           0.1.1
  @backstage/plugin-search-backend-module-pg                0.5.6
  @backstage/plugin-search-backend-module-techdocs          0.1.1
  @backstage/plugin-search-backend-node                     1.2.1
  @backstage/plugin-search-backend                          1.3.1
  @backstage/plugin-search-common                           1.2.3
  @backstage/plugin-search-react                            1.6.0
  @backstage/plugin-search                                  1.3.0
  @backstage/plugin-tech-radar                              0.6.4
  @backstage/plugin-techdocs-backend                        1.6.2
  @backstage/plugin-techdocs-module-addons-contrib          1.0.13
  @backstage/plugin-techdocs-node                           1.7.1
  @backstage/plugin-techdocs-react                          1.1.6
  @backstage/plugin-techdocs                                1.6.2
  @backstage/plugin-user-settings                           0.7.3
  @backstage/plugin-vault-backend                           0.3.1
  @backstage/plugin-vault                                   0.1.12
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.3.1
  @backstage/theme                                          0.2.19, 0.3.0
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.4

**Comment by jonathan-arenas-edo** [comment] 2023-06-08 11:43
Hi,

I found on path: node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js the query definition:

```
const query = SELECT
                    DATE_TRUNC(DATE(usage_start_time), ${BillingExportTypes_1.GCP_QUERY_GROUP_BY[grouping]}) as timestamp,
                    project.id as accountId,
                    project.name as accountName,
                    ifnull(location.region, location.location) as region,
                    service.description as serviceName,
                    sku.description as usageType,
                    usage.unit as usageUnit,
                    system_labels.value AS machineType,
                    SUM(usage.amount) AS usageAmount,
                    SUM(cost) AS cost
                    ${tagPropertySelections}
                    ${labelPropertySelections}
                    ${projectLabelPropertySelections}
                  FROM
                    \`${this.tableName}\`
                  LEFT JOIN
                    UNNEST(system_labels) AS system_labels
                    ON system_labels.key = "compute.googleapis.com/machine_spec"
                  ${tagPropertyJoins}
                  ${labelPropertyJoins}
                  ${projectLabelPropertyJoins}
                  WHERE
                    cost_type != 'rounding_error'
                    AND usage.unit IN ('byte-seconds', 'seconds', 'bytes', 'requests')
                    AND usage_start_time BETWEEN TIMESTAMP('${moment_1.default`
```

What is this system_labels? this is a label on GCP?

Kind regards.

**Comment by jonathan-arenas-edo** [comment] 2023-06-13 07:24
Hi guys! Anyone know how to it works? I can't get it to work.

<img width="942" alt="image" src="https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/assets/118807917/20fe625f-97fb-455f-8bb6-902c94d7a5f9">

`2023-06-13T07:24:09.705Z [api] error: Unable to process footprint request.Error: BigQuery create Query Job failed. Reason: invalidQuery, Location: query, Message: Unrecognized name: system_labels at [18:28]
    at BillingExportTable.createQueryJob (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:384:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BillingExportTable.getUsage (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:357:21)
    at async BillingExportTable.getEstimates (/app/node_modules/@cloud-carbon-footprint/gcp/dist/lib/BillingExportTable.js:30:27)
    at async Object.getCostAndEstimates (/app/node_modules/@cloud-carbon-footprint/app/dist/App.js:52:35)
    at async Promise.all (index 0)
    at async getEstimatesForMissingDates (/app/node_modules/@cloud-carbon-footprint/app/dist/Cache.js:52:13)
    at async App.descriptor.value (/app/node_modules/@cloud-carbon-footprint/app/dist/Cache.js:29:24)
    at async FootprintApiMiddleware (/app/node_modules/@cloud-carbon-footprint/api/dist/api.js:34:35) `

**Comment by ccasher** [comment] 2023-06-20 18:48
Hi @jarenasla-edo, would you mind letting us know what version of `@cloud-carbon-footprint/common` you are using? This may need to be updated because this error seems to be config related.

Also, do you know if you currently have any tags or configured in the app's config?

Finally, system_labels is a property within the BillingExport Table that can be used as a method for tagging resources. CCF supports including these tags in your usage data if you specify it in your config. However, you should not be seeing them if you have not enabled or specified a tag to include.

**Comment by jonathan-arenas-edo** [comment] 2023-06-21 10:04
Hi @ccasher , thanks for your comment and help.

I am working with the latest carbon footprint version:
@cloud-carbon-footprint/backstage-plugin-frontend@0.0.8
@cloud-carbon-footprint/backstage-plugin-backend@0.1.1
@cloud-carbon-footprint/common": "^1.11.0

Maybe is a problem of structure on me bigquery? I am looking for the system_labels property on it, but is not present.
But this is an optional label as I understood.

Structure BigQuery Dataset
```
usage_month	DATE	NULLABLE				
billing_account_id	STRING	NULLABLE				
project	RECORD	NULLABLE				
  number	STRING	NULLABLE				
  id	STRING	NULLABLE				
service	RECORD	NULLABLE				
  id	STRING	NULLABLE				
  description	STRING	NULLABLE				
location	RECORD	NULLABLE				
  location	STRING	NULLABLE				
  region	STRING	NULLABLE				
carbon_footprint_kgCO2e	RECORD	NULLABLE				
  scope1	FLOAT	NULLABLE				
  scope2	RECORD	NULLABLE	
    location_based	FLOAT	NULLABLE
    market_based	FLOAT	NULLABLE
  scope3	FLOAT	NULLABLE				
carbon_footprint_total_kgCO2e	RECORD	NULLABLE				
  after_offsets	FLOAT	NULLABLE				
  market_based	FLOAT	NULLABLE				
  location_based	FLOAT	NULLABLE				
carbon_offsets_kgCO2e	FLOAT	NULLABLE				
carbon_model_version	INTEGER NULLABLE
```

If I backstage up on my local env I can see some errors about it:

```
[0] <i> [webpack-dev-middleware] wait until bundle finished: /tech-radar
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (node:39566) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jonathan/Repositorios/backstahe-app/git/backstage/node_modules/@cloud-carbon-footprint/core/dist/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
[1] (node:39566) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
```

**Comment by jonathan-arenas-edo** [comment] 2023-06-22 06:30
Hi @ccasher Finally I found my problem.

I exported the data from corbon footpring to a dataset on BigQuery, and the plugin doesn't need to be configured with it, but with the dataset for invoice export: gcp_billing_export_v1_01B22A_05AA4C_87BDAC.

Maybe the documentation needs to specify more about the dataset to use, or maybe I didn't understand that part.

Thanks very much for your time.

**Comment by 4upz** [comment] 2023-06-22 15:42
Hi @jarenasla-edo thanks for following up with your fix! Sorry for the confusion -- CCF calculates its own carbon estimates, so the exported data should indeed be the billing data and not Google's own carbon data. 

Perhaps we can make this more clear in the documentation. However, are you referring to just the backstage plugin's documentation? Or are you referring to the [full documentation](cloudcarbonfootprint.org)? 

If only the plugin, perhaps we can improve linking to the full setup instructions as I believe the billing data setup is more clear there.

**Comment by jonathan-arenas-edo** [comment] 2023-06-22 17:34
Hi @4upz ,

I refer only the part of plug in. The documentation is ok but I think is some parts are missing to be defined.
Some documentation you need find inside of code and maybe is interesting to add to main.

For example the cache config or the extra variables that you can use on cloudCarbonFootprint.
In my case these options more the part of CCF calculates It would have been of great interest to me.

Great job with the plugin :)

Kind regards

**Comment by 4upz** [comment] 2023-06-22 21:16
@jarenasla-edo Thanks for the feedback! I can see your point about the config variables. We can definitely improve the plugin's documentation to make this more clear.

If you have any other feedback on other specific parts of the documentation that may be confusing, please feel free to share so that we can continue to improve them!

Since the issue is resolved, I'll go ahead and close this issue.

**Closed as completed by 4upz** 2023-06-22 21:16 UTC
