### ISSUE TITLE
Unable to see backstage sidebar through CCF plugin

### ISSUE THREAD

**Issue by LvffY** [cloud-carbon-footprint/ccf-backstage-plugin#11] opened 2022-06-23 08:41 UTC
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:** Windows 10 Enterprise 20H2 build 19042.1706
- **Browser:** Chrome

### Expected Behavior

After initializing CCF plugin, when going on `/cloud-carbon-footprint` I should see my backstage sidebar. 

### Actual Behavior

After initializing CCF plugin, when going on `/cloud-carbon-footprint` I don't see my backstage sidebar. Only after going on the 

### To Reproduce

Just install CCF backstage plugin as described in the documentation.

Configure only Azure analysis. 

### Screenshots

- First screen

![image](https://user-images.githubusercontent.com/37327656/175253686-b94295b4-52e9-4ae3-aec5-fbf87bc73ace.png)

- Screen on **Carbon intensity map**

![image](https://user-images.githubusercontent.com/37327656/175253906-597b0626-44cf-4349-8a51-ed7a3e7cce35.png)

- Go again on the first screen

![image](https://user-images.githubusercontent.com/37327656/175255674-b051d684-96fa-4270-80e4-b35b9c9f8014.png)

### Additional Information

Could be related to the problem explained in #9 ?

**Comment by 4upz** [comment] 2022-07-11 20:54
Hi @LvffY, this is definitely weird behavior and shouldn't be tied to the issue you mentioned as those are Azure service warnings and this seems to be a UI issue. I'll try to replicate and look into this

**Comment by LvffY** [comment] 2022-07-13 08:01
@4upz To be explicit : *I have other plugins that run well, so this should not be relevant but* my backstage app is running inside an Azure Web App through a docker image.

**Comment by LvffY** [comment] 2022-08-14 07:25
@4upz @ericksod do you have any update on this issue ?

**Comment by 4upz** [comment] 2022-09-21 21:48
Hi @LvffY , are you still seeing this issue? If so, I have two follow-up questions that could help me reproduce it:

- If you're still seeing this happen, can you tell me what the dropdown of the error shown on the screen says?
- Since this is a UI issue, it may also be helpful to see if any errors are being shown in the browser console when this occurs. Would you mind sharing a screenshot of what you see in console when you open up the dev tools of your browser?

**Comment by LvffY** [comment] 2022-09-22 08:43
Hi @4upz 

> * If you're still seeing this happen, can you tell me what the dropdown of the error shown on the screen says?

Yes I'm still seeing the issue. It says the same error as in #13.

> * Since this is a UI issue, it may also be helpful to see if any errors are being shown in the browser console when this occurs. Would you mind sharing a screenshot of what you see in console when you open up the dev tools of your browser?

![image](https://user-images.githubusercontent.com/37327656/191700897-b947591a-b361-4e1e-b13d-a2de2bbaa1e9.png)

**Comment by 4upz** [comment] 2022-10-20 13:12
Closing as this will most likely be resolved with Issue https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/issues/13 and doing a stable migration to the latest version of Backstage. Feel free to reopen or leave a new comment if the sidebar issue persists after migration

**Closed as completed by 4upz** 2022-10-20 13:12 UTC
Labels: bug
