### ISSUE TITLE
Cannot read properties from undefined (reading 'map')

### ISSUE THREAD

**Issue by LvffY** [cloud-carbon-footprint/ccf-backstage-plugin#13] opened 2022-09-08 10:53 UTC
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - Azure Web App (I think Ubuntu, but not sure)
- **Browser:**
  - Chrome
### Expected Behavior

I should have my cloud carbon footprint estimation.

### Actual Behavior

I only get an error message withtout any of the estimation. But it seems that my Azure services are fetch correctly, so this could indicate that my Azure configuration is fine. 

### To Reproduce

- Use the last **Backstage** version
- Use the last **ccf-backstage-plugin** version
- Configure the azure connection

```yaml
cloudCarbonFootprint:
  client:
    dateRangeType: months
    dateRangeValue: 1
    groupBy: week
  azure:
    useBillingData: true
    clientId: ${AZURE_CLIENT_ID}
    clientSecret: ${AZURE_CLIENT_SECRET}
    tenantId: ${AZURE_TENANT_ID}
```

- Start the server, and go to the ccf page.

### Screenshots

- The error

![image](https://user-images.githubusercontent.com/37327656/189103567-4a21f8b8-dfba-4f95-a120-1abb6902226c.png)

- Logs
-
![image](https://user-images.githubusercontent.com/37327656/189103681-a2f08b3d-5504-4516-9ef5-63754f104ea9.png)

- The services (which seem to indicate my Azure resources, so the configuration should be fine)

![image](https://user-images.githubusercontent.com/37327656/189103867-1f7af6ed-17b5-4cf6-9e0f-3e5307d5887e.png)

### Additional Information

© 2022 Thoughtworks, Inc.

**Comment by LvffY** [comment] 2022-09-14 05:54
@4upz @4upz-tw did you have time to check on this ?

**Comment by 4upz** [comment] 2022-09-20 13:25
Hi @LvffY , sorry for going quiet on this! We started looking at your other issue but had to prioritize another urgent improvement needed  for CCF. Now that the work is winding down, we'll be able to continue looking into the sidebar issue along with this one soon. Thanks for your patience!

**Comment by 4upz** [comment] 2022-09-21 21:43
Hi @LvffY, I'm having some trouble reproducing this error using our Azure credentials and the same date range. By looking at the logs, it seems that estimations were fetched but something happens while setting the cache. Can you answer the following questions to help isolate the issue:

- Did this error occur the first time you fetched estimates? Or only on subsequent times?
- Does this error repeat every time you try to load the dashboard?
- In your `packages/backend` folder of your Backstage project, do you see a file named `estimates.cache.week.json`? If so, does it have estimates in it or is it empty?
- Lastly, if you have an estimates file, can you try deleting it and reloading the dashboard? Does the error occur again after it creates a new cache file?

Sorry for all of the follow-up questions, and thanks in advance for helping us isolate this!

**Comment by LvffY** [comment] 2022-09-22 08:33
No worries :) @4upz 

> * Did this error occur the first time you fetched estimates? Or only on subsequent times?

It happens every time

> * Does this error repeat every time you try to load the dashboard?

Yes

> * In your `packages/backend` folder of your Backstage project, do you see a file named `estimates.cache.week.json`? If so, does it have estimates in it or is it empty?

I see a file but it only contains  : 

```json
[]
```

> * Lastly, if you have an estimates file, can you try deleting it and reloading the dashboard? Does the error occur again after it creates a new cache file?

Same error

**Comment by 4upz** [comment] 2022-09-22 22:50
@LvffY Thanks for the quick response. The fact that your cache file is empty is interesting. If you're seeing services on the dashboard, that means that the estimates are in fact making it to the client as the list of services are pulled from the resulting estimates. I'm wondering if this is an error occurring on the client when trying to display the estimates, or weird behavior with the cache when it tries to save them.

To help confirm this and whether the API is returning the expected data -- would you mind reloading the page once more while the browser devtools are open, navigate to the network tab, and showing me what you see as the direct response from the API after the request is completed? Here's a screenshot as an example:

![Screen Shot 2022-09-22 at 6 45 39 PM](https://user-images.githubusercontent.com/26828838/191864724-853f50fa-69ae-4c87-84a1-3cd830b85ce4.png)

**Comment by LvffY** [comment] 2022-09-23 13:44
Hi @4upz 

It seems that I get an answer : 

![image](https://user-images.githubusercontent.com/37327656/191974563-554e9687-8d24-4460-a202-a7d62aaea5dd.png)

**Comment by 4upz** [comment] 2022-10-10 13:49
Hi @LvffY , sorry for the delay. We just did a release that updated the plugin with the latest release of CCF along with some other outdated dependencies. Would you mind updating your ccf plugin to the latest version, then giving it another try and seeing if you see the issue?

Additionally, it would be helpful if you tried running the plugin with a local (non-Azure hosted) version of the app to see if you see the issue as well. If the issue is persisting, this could help us isolate whether the issue is environment or not.

**Comment by LvffY** [comment] 2022-10-14 20:47
Hi @4upz 

After upgrading backstage to `1.7.0.next.2`, reinstalling this plugin and running `yarn dev` on my local machine I have the following issue : 

![image](https://user-images.githubusercontent.com/37327656/195940739-5eb42c9c-1e05-430e-9fa0-5090153b6ca5.png)

Is there any I'm missing ?

**Comment by 4upz** [comment] 2022-10-19 14:25
@LvffY This seems to be a separate issue caused by potential conflicts in the version of react-router that Backstage has just added to the next version of their app, and the version that our plugin uses from the previous scaffolder. We did just make a release, in which you can try to update your plugin when it publishes and see if it resolves that issue. Otherwise, I would try cleaning your cache or deleting your `node_modules` folder and doing a fresh install to try to clear the conflicts.

If the issue still persists, we can look into that separately as that would involve a deeper look into troubleshooting and updating to the next version of Backstage's create-app. For the scope of the issue, I would try to testing the current version of the app with the most stable release of Backstage (1.7.0) to see if you still encounter the original error. That way, we're minimizing environmental variables. We recommend using the stable version (not using the `--release next` flag) instead of the Next version, as that is the release we often test against.

**Comment by LvffY** [comment] 2022-10-19 21:15
@4upz I updated the backstage to 1.7.0 and add the ccf plugin. But I got the same kind of errors : 

- UI

![image](https://user-images.githubusercontent.com/37327656/196805315-eb96609a-1147-4388-9c3d-42efa9396798.png)


- Logs

![image](https://user-images.githubusercontent.com/37327656/196805261-e97c1a58-d46c-456c-89a2-7ba1e5f8100b.png)

Do you think I'm (again) missing something ?

**Comment by 4upz** [comment] 2022-10-19 21:29
@LvffY The logs in the second image seem to only be sub-dependency warnings. So I wouldn't worry about those as they shouldn't be breaking the app. However, the browser error in the first image is interesting, yet it doesn't mention the plugin in the error trace and only Backstage core.

I think there's still a mismatch in dependencies going on that is separate from the plugin. Regardless, it may be more productive to hop on a call to truly understand what's happening. If you're interested, do you want to send me an email at arik.smith@thoughtworks.com and perhaps we can find some time to hop on a call and troubleshoot?

**Comment by LvffY** [comment] 2022-10-20 05:36
@4upz Thanks, it would be easier :)

Because I think this new problem is somehow related to the `1.7.0` version, I opened a backstage issue (https://github.com/backstage/backstage/issues/14239) about that. When it will be resolved, I'll retry about your issue here and reach out to you on your mail :)

**Comment by 4upz** [comment] 2022-10-20 13:11
@LvffY Sounds good, I'll go ahead and close this issue for now. But if it persists, after you fix the Backstage issue then feel free to reopen it, leave a new comment, or send me an email 😃

**Closed as completed by 4upz** 2022-10-20 13:11 UTC
